(() => {
  const API = "/api/v1";
  const state = { companies: [], selectedCompany: null, experience: null, activeTab: "branding" };
  const tabs = [["branding","Branding"],["localization","Idiomas"],["launchpad","Launchpad"],["widgets","Widgets"],["sections","Secciones"],["actions","Acciones rápidas"],["fields","Campos configurables"],["alerts","Alertas"],["preview","Vista previa Panel Empresa"]];
  const collections = {
    launchpad:{key:"launchpad_cards",endpoint:"launchpad-cards",addLabel:"Agregar tarjeta",blank:{enabled:true,title_key:"Nueva tarjeta",subtitle_key:"",module_code:"core",card_code:"new_card",route_path:"/client",position:99,size:"medium",action_type:"navigate",settings_json:{}},cols:[["enabled","bool"],["title_key","text"],["subtitle_key","text"],["module_code","text"],["card_code","text"],["route_path","text"],["position","number"],["size","size"],["action_type","action_type"]]},
    widgets:{key:"widgets",endpoint:"crm-widgets",addLabel:"Agregar widget",blank:{enabled:true,title_key:"Nuevo widget",module_code:"kpis",widget_code:"new_widget",metric_source:"manual",position:99,size:"medium",settings_json:{}},cols:[["enabled","bool"],["title_key","text"],["module_code","text"],["widget_code","text"],["metric_source","text"],["position","number"],["size","size"]]},
    sections:{key:"sections",endpoint:"crm-sections",addLabel:"Agregar sección",blank:{enabled:true,title_key:"Nueva sección",module_code:"core",section_code:"new_section",route_path:"/client/section",section_type:"page",position:99,settings_json:{}},cols:[["enabled","bool"],["title_key","text"],["module_code","text"],["section_code","text"],["route_path","text"],["section_type","section_type"],["position","number"]]},
    actions:{key:"actions",endpoint:"crm-actions",addLabel:"Agregar acción",blank:{enabled:true,title_key:"Nueva acción",module_code:"core",action_code:"new_action",target:"/client",action_type:"navigate",position:99,settings_json:{}},cols:[["enabled","bool"],["title_key","text"],["module_code","text"],["action_code","text"],["target","text"],["action_type","action_type"],["position","number"]]},
    fields:{key:"field_configs",endpoint:"field-configs",addLabel:"Agregar campo",blank:{enabled:true,required:false,module_code:"core",entity_code:"entity",field_code:"new_field",label_key:"Nuevo campo",field_type:"text",position:99,options_json:{},validation_json:{},settings_json:{}},cols:[["enabled","bool"],["required","bool"],["module_code","text"],["entity_code","text"],["field_code","text"],["label_key","text"],["field_type","field_type"],["position","number"]]},
    alerts:{key:"alert_rules",endpoint:"alert-rules",addLabel:"Agregar alerta",blank:{enabled:true,module_code:"core",rule_code:"new_alert",event_type:"manual",severity:"info",display_type:"toast",message_key:"Nueva alerta",condition_json:{},settings_json:{}},cols:[["enabled","bool"],["module_code","text"],["rule_code","text"],["event_type","text"],["severity","severity"],["display_type","display_type"],["message_key","text"]]}
  };
  const opts = {size:["small","medium","large","wide"],action_type:["navigate","modal","api","export","external"],section_type:["page","table","kanban","chart","form","report","config"],field_type:["text","number","money","select","boolean","date","datetime","phone","email","textarea"],severity:["info","success","warning","danger"],display_type:["toast","modal","banner","badge","card_alert"]};
  const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function toast(msg,ok=true){const e=document.createElement("div");e.className=`clx-builder-toast ${ok?"ok":"err"}`;e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),4200)}
  async function api(path,opt={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.detail||d?.error||t||`HTTP ${r.status}`);return d}
  const cname=c=>c?.name||c?.legal_name||c?.display_name||c?.slug||c?.id||"Empresa";
  const cslug=c=>c?.slug||c?.code||"";
  async function loadCompanies(){try{const d=await api(`${API}/companies`);state.companies=Array.isArray(d)?d:(d.items||d.companies||[]);decorateCompanyButtons();return state.companies}catch{return[]}}
  function ensureModal(){if(qs("#clx-crm-builder-modal"))return;const m=document.createElement("div");m.id="clx-crm-builder-modal";m.className="clx-crm-builder-modal";m.innerHTML=`<div class="clx-crm-builder-shell"><div class="clx-builder-head"><div><div id="clx-builder-company-name" class="clx-builder-title">CRM Builder</div><div id="clx-builder-company-sub" class="clx-builder-sub">Panel Empresa</div></div><div class="clx-builder-actions"><button id="clx-builder-defaults" class="clx-builder-btn ok">Regenerar defaults</button><button id="clx-builder-refresh" class="clx-builder-btn">Refrescar</button><button id="clx-builder-close" class="clx-builder-btn danger">Cerrar</button></div></div><div id="clx-builder-tabs" class="clx-builder-tabs"></div><div id="clx-builder-body" class="clx-builder-body"></div></div>`;document.body.appendChild(m);qs("#clx-builder-close").onclick=()=>m.classList.remove("is-open");qs("#clx-builder-refresh").onclick=async()=>{await loadExperience();render();toast("Actualizado")};qs("#clx-builder-defaults").onclick=ensureDefaults;m.onclick=e=>{if(e.target===m)m.classList.remove("is-open")}}
  function ensureGlobalLauncher(){if(qs("#clx-crm-builder-global-launcher"))return;const b=document.createElement("button");b.id="clx-crm-builder-global-launcher";b.className="clx-builder-btn primary";b.textContent="CRM Builder";b.style.cssText="position:fixed;right:18px;bottom:82px;z-index:5000";b.onclick=async()=>{await loadCompanies();state.companies.length===1?openBuilder(state.companies[0]):openPicker()};document.body.appendChild(b)}
  function findCompanyId(){const m=document.body.innerText.match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i);return m?m[0]:null}
  function decorateCompanyButtons(){qsa("[data-company-id]").forEach(row=>{if(row.querySelector(".clx-builder-launcher"))return;const id=row.dataset.companyId;if(!id)return;const b=document.createElement("button");b.className="clx-builder-launcher";b.textContent="Configurar CRM";b.onclick=e=>{e.preventDefault();e.stopPropagation();openById(id)};row.appendChild(b)});qsa("button,a").filter(e=>/configurar crm|crm builder/i.test(e.textContent||"")).forEach(b=>{if(b.dataset.clxBound)return;b.dataset.clxBound="1";b.addEventListener("click",e=>{const id=b.dataset.companyId||b.closest("[data-company-id]")?.dataset.companyId||state.selectedCompany?.id||findCompanyId();if(id){e.preventDefault();e.stopPropagation();openById(id)}},true)})}
  function openPicker(){ensureModal();qs("#clx-builder-company-name").textContent="Seleccionar empresa";qs("#clx-builder-company-sub").textContent="Elige empresa para configurar Panel Empresa";qs("#clx-builder-tabs").innerHTML="";qs("#clx-builder-body").innerHTML=(state.companies||[]).map(c=>`<button class="clx-builder-btn" data-picker="${esc(c.id)}">${esc(cname(c))} <span class="clx-builder-muted">${esc(cslug(c))}</span></button>`).join("")||"<div class='clx-builder-muted'>Sin empresas</div>";qsa("[data-picker]").forEach(b=>b.onclick=()=>openById(b.dataset.picker));qs("#clx-crm-builder-modal").classList.add("is-open")}
  async function openById(id){await loadCompanies();await openBuilder(state.companies.find(c=>String(c.id)===String(id))||{id})}
  async function openBuilder(company){ensureModal();state.selectedCompany=company;state.activeTab="branding";qs("#clx-builder-company-name").textContent=`CRM Builder · ${cname(company)}`;qs("#clx-builder-company-sub").textContent=`Panel Empresa · ${company.id}`;qs("#clx-crm-builder-modal").classList.add("is-open");await loadExperience();render()}
  async function loadExperience(){try{state.experience=await api(`${API}/companies/${state.selectedCompany.id}/experience`)}catch(e){state.experience=null;toast(`Error experience: ${e.message}`,false)}}
  async function ensureDefaults(){try{await api(`${API}/companies/${state.selectedCompany.id}/experience/ensure-defaults`,{method:"POST"});await loadExperience();render();toast("Defaults regenerados sin duplicar")}catch(e){toast(e.message,false)}}
  function render(){renderTabs();const body=qs("#clx-builder-body");if(!state.experience){body.innerHTML="<div class='clx-builder-muted'>No cargó experience</div>";return}if(state.activeTab==="branding")return renderBranding(body);if(state.activeTab==="localization")return renderLocalization(body);if(state.activeTab==="preview")return renderPreview(body);return renderCollection(body,state.activeTab)}
  function renderTabs(){const h=qs("#clx-builder-tabs");h.innerHTML=tabs.map(([id,l])=>`<button class="clx-builder-tab ${state.activeTab===id?"active":""}" data-tab="${id}">${l}</button>`).join("");qsa("[data-tab]",h).forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;render()})}
  function field(id,label,val,type="text"){return`<div class="clx-builder-field"><label>${esc(label)}</label><input id="branding-${esc(id)}" type="${type}" value="${esc(val)}"></div>`}
  function selectField(id,label,val,os){return`<div class="clx-builder-field"><label>${esc(label)}</label><select id="branding-${esc(id)}">${os.map(o=>`<option value="${esc(o)}" ${String(val)===o?"selected":""}>${esc(o)}</option>`).join("")}</select></div>`}
  function renderBranding(body){const b=state.experience.branding||{};body.innerHTML=`<div class="clx-builder-toolbar"><div><div class="clx-builder-title">Branding del Panel Empresa</div><div class="clx-builder-muted">Estos colores definen cómo se verá el CRM del cliente.</div></div><button class="clx-builder-btn primary" id="save-branding">Guardar branding</button></div><div class="clx-builder-form">${["logo_url","primary_color","secondary_color","background_color","card_color","text_color","button_color","status_color","success_color"].map(k=>field(k,k.replaceAll("_"," "),b[k]||(["logo_url"].includes(k)?"":"#050505"),k==="logo_url"?"text":"color")).join("")}${selectField("theme_mode","Modo",b.theme_mode||"dark",["dark","light"])}${selectField("industry_theme","Industry theme",b.industry_theme||"default",["default","field","hospitality","retail","production"])}${selectField("visual_preset","Visual preset",b.visual_preset||"clonexa_default",["clonexa_default","field_ops_dark","hospitality_night_ops","retail_pastel_performance","production_neon"])}</div><div class="clx-builder-field" style="margin-top:14px"><label>Logo palette JSON</label><textarea id="branding-logo_palette_json" rows="5">${esc(JSON.stringify(b.logo_palette_json||{},null,2))}</textarea></div>`;qs("#save-branding").onclick=saveBranding}
  function renderLocalization(body){const l=state.experience.localization||{},langs=new Set(l.enabled_languages||["es","en","fr"]);body.innerHTML=`<div class="clx-builder-toolbar"><div><div class="clx-builder-title">Idiomas</div><div class="clx-builder-muted">Idioma principal y disponibles.</div></div><button class="clx-builder-btn primary" id="save-localization">Guardar idiomas</button></div><div class="clx-builder-form">${selectField("default_language","Idioma principal",l.default_language||"es",["es","en","fr"])}${["es","en","fr"].map(x=>`<label class="clx-builder-field"><span>${x==="es"?"Español":x==="en"?"English":"Français"}</span><input type="checkbox" id="lang-${x}" ${langs.has(x)?"checked":""}></label>`).join("")}</div>`;qs("#save-localization").onclick=saveLocalization}
  function cell(k,t,v){if(t==="bool")return`<label><input data-field="${esc(k)}" type="checkbox" ${v?"checked":""}></label>`;if(opts[t])return`<select data-field="${esc(k)}">${opts[t].map(o=>`<option value="${esc(o)}" ${String(v||"")===o?"selected":""}>${esc(o)}</option>`).join("")}</select>`;return`<input data-field="${esc(k)}" type="${t==="number"?"number":"text"}" value="${esc(v??"")}">`}
  function renderCollection(body,tab){const c=collections[tab],items=[...(state.experience[c.key]||[])].sort((a,b)=>(a.position||0)-(b.position||0));body.innerHTML=`<div class="clx-builder-toolbar"><div><div class="clx-builder-title">${c.addLabel.replace("Agregar ","")}</div><div class="clx-builder-muted">Crear, editar, eliminar y ordenar configuración real.</div></div><div class="clx-builder-actions"><button class="clx-builder-btn ok" id="add-item">${c.addLabel}</button><button class="clx-builder-btn" id="reset-defaults">Regenerar defaults</button></div></div>${items.map(i=>`<div class="clx-builder-row" data-id="${esc(i.id)}">${c.cols.map(([k,t])=>cell(k,t,i[k])).join("")}<div class="clx-builder-actions"><button class="clx-grid-btn primary" data-save>Guardar</button><button class="clx-grid-btn danger" data-del>Eliminar</button></div></div>`).join("")||"<div class='clx-builder-muted'>Sin elementos. Usa Regenerar defaults.</div>"}`;qs("#add-item").onclick=()=>createItem(tab);qs("#reset-defaults").onclick=ensureDefaults;qsa("[data-save]",body).forEach(b=>b.onclick=()=>saveRow(tab,b.closest("[data-id]")));qsa("[data-del]",body).forEach(b=>b.onclick=()=>deleteRow(tab,b.closest("[data-id]")))}
  function rowPayload(row){const p={};qsa("[data-field]",row).forEach(i=>{p[i.dataset.field]=i.type==="checkbox"?i.checked:i.type==="number"?Number(i.value||0):i.value});return p}
  async function createItem(tab){const c=collections[tab],p={...c.blank};const code=Object.keys(p).find(k=>k.endsWith("_code"));if(code)p[code]=`${p[code]}_${Date.now()}`;try{await api(`${API}/companies/${state.selectedCompany.id}/${c.endpoint}`,{method:"POST",body:JSON.stringify(p)});await loadExperience();render();toast("Creado")}catch(e){toast(e.message,false)}}
  async function saveRow(tab,row){const c=collections[tab];try{await api(`${API}/companies/${state.selectedCompany.id}/${c.endpoint}/${row.dataset.id}`,{method:"PUT",body:JSON.stringify(rowPayload(row))});await loadExperience();render();toast("Guardado")}catch(e){toast(e.message,false)}}
  async function deleteRow(tab,row){if(!confirm("Eliminar?"))return;const c=collections[tab];try{await api(`${API}/companies/${state.selectedCompany.id}/${c.endpoint}/${row.dataset.id}`,{method:"DELETE"});await loadExperience();render();toast("Eliminado")}catch(e){toast(e.message,false)}}
  async function saveBranding(){const keys=["logo_url","primary_color","secondary_color","background_color","card_color","text_color","button_color","status_color","success_color","theme_mode","industry_theme","visual_preset"],p={};keys.forEach(k=>{const e=qs(`#branding-${k}`);if(e)p[k]=e.value});try{p.logo_palette_json=JSON.parse(qs("#branding-logo_palette_json").value||"{}")}catch{return toast("JSON inválido",false)}try{await api(`${API}/companies/${state.selectedCompany.id}/branding`,{method:"PUT",body:JSON.stringify(p)});await loadExperience();render();toast("Branding guardado")}catch(e){toast(e.message,false)}}
  async function saveLocalization(){const p={default_language:qs("#branding-default_language").value,enabled_languages:["es","en","fr"].filter(l=>qs(`#lang-${l}`)?.checked)};try{await api(`${API}/companies/${state.selectedCompany.id}/localization`,{method:"PUT",body:JSON.stringify(p)});await loadExperience();render();toast("Idiomas guardados")}catch(e){toast(e.message,false)}}
  function enabled(k){return(state.experience[k]||[]).filter(i=>i.enabled!==false).sort((a,b)=>(a.position||0)-(b.position||0))}
  function renderPreview(body){const x=state.experience,b=x.branding||{},l=x.localization||{},co=state.selectedCompany||{};body.innerHTML=`<div class="clx-builder-toolbar"><div><div class="clx-builder-title">Así verá el panel esta empresa</div><div class="clx-builder-muted">Preview operativa con datos reales del CRM Builder.</div></div><button class="clx-builder-btn" id="reset-defaults">Regenerar defaults</button></div><div class="clx-preview-shell" style="--clx-preview-bg:${esc(b.background_color||"#050505")};--clx-preview-card:${esc(b.card_color||"#18181b")};--clx-preview-text:${esc(b.text_color||"#f8fafc")};--clx-preview-primary:${esc(b.primary_color||"#ef233c")};--clx-preview-success:${esc(b.success_color||"#00ff88")};background:radial-gradient(circle at 10% 0%,${esc(b.primary_color||"#ef233c")}33,transparent 32%),radial-gradient(circle at 85% 0%,${esc(b.secondary_color||"#ff2bd6")}28,transparent 28%),${esc(b.background_color||"#050505")};color:${esc(b.text_color||"#f8fafc")}"><div class="clx-preview-top"><div><div class="clx-preview-brand">${esc(cname(co))}</div><div class="clx-builder-muted">Panel Empresa · ${esc(b.industry_theme||"default")} · ${esc(b.visual_preset||"clonexa_default")} · idioma ${esc(l.default_language||"es")}</div></div><div class="clx-preview-badge">LIVE / READY</div></div>${previewBlock("Launchpad","clx-preview-cards",enabled("launchpad_cards"),i=>`<div class="clx-preview-card"><strong>${esc(i.icon||"⬡")} ${esc(i.title_key)}</strong><div class="clx-builder-muted">${esc(i.subtitle_key||i.route_path||"")}</div></div>`)}${previewBlock("Widgets de métricas","clx-preview-widgets",enabled("widgets"),(i,n)=>`<div class="clx-preview-widget"><strong>${esc(i.title_key)}</strong><div style="font-size:26px;font-weight:950;margin-top:8px">${["24","8","$4.2M","91%","12"][n%5]}</div><div class="clx-builder-muted">${esc(i.metric_source||i.widget_code)}</div></div>`)}${previewBlock("Acciones rápidas","clx-preview-actions",enabled("actions"),i=>`<div class="clx-preview-action">⚡ ${esc(i.title_key)}</div>`)}${previewBlock("Secciones principales","clx-preview-sections",enabled("sections"),i=>`<div class="clx-preview-section">${esc(i.title_key)} <span class="clx-builder-muted">· ${esc(i.section_type)}</span></div>`)}${previewBlock("Alertas visibles","clx-preview-alerts",enabled("alert_rules"),i=>`<div class="clx-preview-alert">${esc(i.severity).toUpperCase()} · ${esc(i.message_key)}</div>`)}</div>`;qs("#reset-defaults").onclick=ensureDefaults}
  function previewBlock(title,cls,items,fn){return`<div class="clx-preview-section-title">${title}</div><div class="${cls}">${items.length?items.map(fn).join(""):"<div class='clx-builder-muted'>Sin elementos activos</div>"}</div>`}
  async function init(){ensureModal();ensureGlobalLauncher();await loadCompanies();decorateCompanyButtons();new MutationObserver(()=>decorateCompanyButtons()).observe(document.body,{childList:true,subtree:true});window.ClonexaCrmBuilder={openById,openPicker,ensureDefaults}}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();
